# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=py37

    - python: 3.6
      env: TOXENV=py36


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
  - tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: discdiver
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: notebooktoall/notebooktoall
    python: 3.6
